[workspace]
members = [
    "taocp-bit",
    "taocp-graph",
    "taocp-graph-apsp",
    "taocp-graph-sssp",
    "taocp-modint",
    "taocp-modint-math",
    "taocp-num-int",
    "taocp-prelude",
    "taocp-union-find",
    "verify",
]
