[package]
name = "procon-rs-modint"
version = "0.1.0"
authors = ["taotao54321 <taotao54321@gmail.com>"]
edition = "2018"

[dependencies]
num-traits = "=0.2.11"

[dev-dependencies]
serial_test = "0.5.1"
