name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Rust toolchain
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/env
          ~/.rustup/settings.toml
          ~/.rustup/toolchains
          ~/.rustup/update-hashes
        key: ${{ runner.os }}-rust-toolchain-${{ hashFiles('rust-toolchain.toml') }}

    - name: Setup Rust toolchain
      id: rust_toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.42.0-x86_64-unknown-linux-gnu
        default: true
        profile: minimal
        components: clippy

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Cache Python environment
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-python-${{ env.pythonLocation }}

    - name: Install online-judge-verify-helper
      run: pip3 install --upgrade --upgrade-strategy eager online-judge-verify-helper

    - name: Cache cargo deps
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/git
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          target
        key: ${{ runner.os }}-cargo-${{ steps.rust_toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.*') }}

    - name: Run cargo clippy
      run: cargo clippy --workspace --bins --tests --examples --

    - name: Run cargo test
      run: cargo test --workspace --

    - name: Cache oj-verify testcases
      uses: actions/cache@v2
      with:
        path: .verify-helper/cache
        key: oj-verify-${{ hashFiles('verify/**/*.rs') }}

    - name: Run oj-verify
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
      run: oj-verify run --jobs 2
