name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust toolchain
      id: rust_toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.42.0-x86_64-unknown-linux-gnu
        default: true
        profile: minimal
        components: clippy

    - name: Cache Rust toolchain
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/env
          ~/.rustup/settings.toml
          ~/.rustup/toolchains
          ~/.rustup/update-hashes
        key: rust-toolchain-${{ steps.toolchain.outputs.rustc_hash }}

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install online-judge-verify-helper
      run: pip3 install --upgrade --upgrade-strategy eager online-judge-verify-helper

    - name: Cache Python environment
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: python-${{ env.pythonLocation }}

    - name: Run cargo build
      run: cargo build

    - name: Run cargo clippy
      run: cargo clippy --workspace --bins --tests --examples --

    - name: Run cargo test
      run: cargo test --workspace --

    - name: Run oj-verify
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
      run: oj-verify run --jobs $(nproc)

    - name: Cache cargo directory
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/git
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          target
        key: cargo-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.*') }}
